
version: '3.4'

services:
  companies-api-db:
    container_name: companies-api-db
    image: mysql:5.7.30
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "companies-api"
    ports:
      - 3306:3306

  companies-api:
    container_name: companies-api
    build:
      context: .
      dockerfile: "./DockerfileDev"
    volumes:
      - ./src:/home/app/src
      - /home/app/node_modules
    image: companies-api
    depends_on:
      - companies-api-db
    environment:
      WAIT_HOSTS: companies-api-db:3306
      PORT: 3000
    ports:
      - 3000:3000
